name: "Github Actions Activity"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_apply
        - Terraform_destroy

jobs:
  terraform_apply:
    name: "Terraform_apply"
    if: ${{ github.event.inputs.action == 'Terraform_apply' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -migrate-state -force-copy

      - name: Terraform Plan
        run: terraform plan -var="username_db=${{ secrets.USERNAME_DB }}" -var="password_db=${{ secrets.PASSWORD_DB }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="username_db=${{ secrets.USERNAME_DB }}" -var="password_db=${{ secrets.PASSWORD_DB }}"

  terraform_destroy:
    name: "Terraform_destroy"
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -migrate-state -force-copy

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var="username_db=${{ secrets.USERNAME_DB }}" -var="password_db=${{ secrets.PASSWORD_DB }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="username_db=${{ secrets.USERNAME_DB }}" -var="password_db=${{ secrets.PASSWORD_DB }}"
